### ISSUE TITLE
LEK MOD CIV drafter 

### ISSUE THREAD

**Issue by hazetgh** [TriDvaRas/Civilizator#3]
Can u add as a new DLC LEK MOD CIV drafter? Like it is possible here:
https://hellblazer-tv.github.io/

woud be very usefull because many ppl play multiplayer with LEK MOD :)

**Comment by TriDvaRas** [comment]
Good idea
Not realy familliar with LEK MOD. Is there something like a wiki of it?

**Comment by hazetgh** [comment]
There is:
main page:
https://docs.google.com/document/d/18tsjg2C1wKA7I41GktDRr6R83eUrhn4FHi9EUEtpKvI/edit

Master List of Civilizations:
https://docs.google.com/document/d/e/2PACX-1vSUkKuhdURg8zS2P4nMHRjXvkp-Tg5QPxvMfaXVoIiyfBgPQxqVaxAeJG9JfZN6HAq9SjYE4NLxjLyk/pub

As i see in the code u propably shoud add new Civs into list:
https://github.com/TriDvaRas/Civilizator/blob/master/assets/CivList.json

And also extend the list of DLC's by adding LEK MOD 24.1.1

**Comment by TriDvaRas** [comment]
Deployed and update
`start` and `fast` commands now have optional arg [game] to change the game
Default is still nomod civ5 
  
 
![image](https://user-images.githubusercontent.com/47600110/90022876-bd3b5a00-dcbb-11ea-8852-c87eaae3d638.png)
![image](https://user-images.githubusercontent.com/47600110/90022913-c6c4c200-dcbb-11ea-9538-89bd7086120e.png)
